### ISSUE TITLE
exnodes not showing up in "Landsat Search" results

### ISSUE THREAD

**Issue by batzli** [datalogistics/ibp_server#14]
Confusing results between the Exnode Browser and the Landsat Search.  I can see Exnodes listed in the browser (such as Landsat/LC8/024/030/2015/LC80240302015180LGN00.jpg) but they don't show up in the Landsat Search.  All results are listed as at USGS only and no Exnode versions are found.

**Comment by disprosium8** [comment]
This issue was moved to datalogistics/dlt-web#2
