### ISSUE TITLE
Calendar GUI in Landsat Search on EODN website not functioning

### ISSUE THREAD

**Issue by batzli** [datalogistics/ibp_server#15]
The calendars for the Landsat Search interface seem to not allow date selection either anymore (they used to work).  Only the "today" button populates the date field now.  I'm using Chrome on Win 7.

**Comment by PerilousApricot** [comment]
@batzli Hey, the web interface isn't a part of the depot software itself, so perhaps this isn't the best place to open these tickets. @disprosium8 -- do you have a better repo out there?

**Comment by batzli** [comment]
oops, sorry.  I don't know.  There must be a better place for website issues... I'm open to suggestions.  Ezra?

**Comment by PerilousApricot** [comment]
Perhaps https://github.com/datalogistics/dlt-web ?

**Comment by disprosium8** [comment]
Yes, these should all be in the dlt-web repo.  I'll see if I can move 
the issues.

**Comment by batzli** [comment]
sorry and thanks!

**Comment by disprosium8** [comment]
This issue was moved to datalogistics/dlt-web#1
